// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8gVXo_PFm1W6fCFV1QKVHEbf1ip4-tPI',
    appId: '1:1063410222826:web:ca9051ce564cf6ea157993',
    messagingSenderId: '1063410222826',
    projectId: 'taskapp-ba2d5',
    authDomain: 'taskapp-ba2d5.firebaseapp.com',
    storageBucket: 'taskapp-ba2d5.appspot.com',
    measurementId: 'G-2B9WYDP52M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANYABu_G3g2sX7QQVY3gLSxARduaehSLs',
    appId: '1:1063410222826:android:d4c8454d3d0709ca157993',
    messagingSenderId: '1063410222826',
    projectId: 'taskapp-ba2d5',
    storageBucket: 'taskapp-ba2d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBq4M5qDlZ39sInSS10t6nz_NzlrMUC1s',
    appId: '1:1063410222826:ios:cf4dd22846b64332157993',
    messagingSenderId: '1063410222826',
    projectId: 'taskapp-ba2d5',
    storageBucket: 'taskapp-ba2d5.appspot.com',
    iosClientId: '1063410222826-i0ah5toq9p8a7v657dteeu4lcbrtua0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBq4M5qDlZ39sInSS10t6nz_NzlrMUC1s',
    appId: '1:1063410222826:ios:19553ee38836b67c157993',
    messagingSenderId: '1063410222826',
    projectId: 'taskapp-ba2d5',
    storageBucket: 'taskapp-ba2d5.appspot.com',
    iosClientId: '1063410222826-igso9dj4j8jf670c1fgspmhb3k8a7i2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolistApp.RunnerTests',
  );
}
