// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfXJ-rK9TOPiY4cyfxVr9nwubsYrsrVRA',
    appId: '1:734509898196:web:bccff1d728fe896e9dde41',
    messagingSenderId: '734509898196',
    projectId: 'taskapp-777c4',
    authDomain: 'taskapp-777c4.firebaseapp.com',
    storageBucket: 'taskapp-777c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhOk-8u6wzUY7QvCKv3W2H6D5pVgcxW1Y',
    appId: '1:734509898196:android:8a02c239e418ff189dde41',
    messagingSenderId: '734509898196',
    projectId: 'taskapp-777c4',
    storageBucket: 'taskapp-777c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdLPPSh5OOPiVOvF01yJDr0Py-vxvEyR0',
    appId: '1:734509898196:ios:8e06ba0c4fd67db99dde41',
    messagingSenderId: '734509898196',
    projectId: 'taskapp-777c4',
    storageBucket: 'taskapp-777c4.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdLPPSh5OOPiVOvF01yJDr0Py-vxvEyR0',
    appId: '1:734509898196:ios:010d95d795eab6839dde41',
    messagingSenderId: '734509898196',
    projectId: 'taskapp-777c4',
    storageBucket: 'taskapp-777c4.appspot.com',
    iosBundleId: 'com.example.todolistApp.RunnerTests',
  );
}
